### model
model_name_or_path: {{Qwen2.5-7B-Instruct Path}}

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: {{examples/deepspeed/ds_z3_config.json from llama-factory}}

### dataset
dataset: cflue_oe_r1,cflue_mcq_r1,fin_qa_r1,ccc_r1
dataset_dir: {{dataset directory}}
template: qwen
cutoff_len: 16384
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 128

### output
output_dir: experiments/checkpoints/Qwen2.5-7B-Instruct-R1
logging_steps: 10
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: linear
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000