### model
model_name_or_path: your_model_path # E.g. Qwen2.5-VL-7B-Instruct
image_max_pixels: 802816
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: false
freeze_multi_modal_projector: false
freeze_language_model: false
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: sealtitle_toolcall_train
template: qwen2_vl
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
## save_steps: 500
output_dir: saves/SealTitle/full_param_toolcall
logging_steps: 10
save_strategy: epoch
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: SealTitle_test
# per_device_eval_batch_size: 2
# eval_strategy: steps
# eval_steps: 20
# val_size: 0.1

